/*
 * SS_xbee.h
 *
 *  Created on: 04.04.2018
 *      Author: Bartuœ
 */

#ifndef SS_GRAZYNA_XBEE_H_
#define SS_GRAZYNA_XBEE_H_

#include "stm32f4xx_hal.h"


#define XBEE_UART huart1
//#define GRAZYNA_LITTLE_ENDIAN
//#define SKIP_CRC
#define GRAZYNA_SET 0x15
#define GRAZYNA_GET 0x05
#define GRAZYNA_INFO 0xD5
extern uint16_t VALID_CAPTURE;
extern struct MS5607 ms5607;
extern uint8_t SET_ALTITUDE;
extern int16_t close_servo_altitude;
extern int32_t ref_pres;
enum  GRAZYNA_HEADER_TYPE{
	GRAZYNA_ABORT,
	GRAZYNA_IGN,
	GRAZYNA_IGN_SEQ,
	GRAZYNA_LAUNCH_SEQUENCE,
	GRAZYNA_POWER_UP,
	GRAZYNA_SET_OX_DELAY = 6,
	GRAZYNA_SET_FUEL_DELAY,
	GRAZYNA_MANIEK_VOLTAGE = 0x0C,
	GRAZYNA_MANIEK_IGN_GET_STATUS,
	GRAZYNA_MANIEK_ARM_GET_STATUS,
	GRAZYNA_MANIEK_DISARM,
	GRAZYNA_BORYS_OX_SERVO_POS = 0x12,
	GRAZYNA_BORYS_OX_SERVO_CLOSED_POS,
	GRAZYNA_BORYS_OX_SERVO_OPENED_POS,
	GRAZYNA_BORYS_OPEN_OX_SERVO,
	GRAZYNA_BORYS_CLOSE_OX_SERVO,
	GRAZYNA_BORYS_GET_OX_SERVO_CURRENT,
	GRAZYNA_BORYS_VENTING_SERVO_CLOSED_POS = 26,
	GRAZYNA_BORYS_VENTING_SERVO_OPENED_POS,
	GRAZYNA_BORYS_OPEN_VENTING_SERVO = 28,
	GRAZYNA_BORYS_CLOSE_VENTING_SERVO,
	GRAZYNA_BORYS_OX_LOAD = 0x25,
	GRAZYNA_BORYS_OX_UNLOAD,
	GRAZYNA_BORYS_OX_VENT = 0x2A,
	GRAZYNA_BORYS_VOLTAGE = 0x3A,
	GRAZYNA_BORYS_IGN_GET_STATUS,
	GRAZYNA_BORYS_ARM_GET_STATUS,
	GRAZYNA_STASZEK_DISARM,
	GRAZYNA_BORYS_ERASE_ALL_FLASH_DATA = 0x3F,
	GRAZYNA_BORYS_ERASE_FLASH = 0x40,
	GRAZYNA_BORYS_STOP_WRITE_MEAS = 0x42,
	GRAZYNA_BORYS_COPY_FLASH_TO_PC,
	GRAZYNA_STASZEK_GET_SD_STATUS = 0x44,
	GRAZYNA_BORYS__LAUNCH_WRITE_ADC_FLASH,
	GRAZYNA_BORYS_START_MEAS,
	GRAZYNA_STASZEK_TENSO_PROP_RAW,
	GRAZYNA_STASZEK_TENSO_PROP_SCALED,
	GRAZYNA_BORYS_FLASH_TARE,
	GRAZYNA_BORYS_TENSO_THRUST_RAW,
	GRAZYNA_BORYS_TENSO_THRUST_SCALED,
	GRAZYNA_STASZEK_TENSO_THRUST_TARE,
	GRAZYNA_STASZEK_PRESS_OX_RAW,
	GRAZYNA_STASZEK_PRESS_OX_SCALED,
	GRAZYNA_STASZEK_PRESS_FUEL_RAW,
	GRAZYNA_STASZEK_PRESS_FUEL_SCALED,

	GRAZYNA_BORYS__LAUNCH_STOP_WRITING_TO_FLASH = 0x57,
	BORYS_TENSO_PROP_RAW=0x64,
	GRAZYNA_BORYS_GET_REFERENCE_PRESSURE = 0x68,
	GRAZYNA_BORYS_GET_ALTITUDE,
	GRAZYNA_BORYS_GET_PRESSURE,
	GRAZYNA_BORYS_SET_ALTITUDE = 112,
	GRAZYNA_BORYS_CZAPLA_ON = 250,
	GRAZYNA_BORYS_CZAPLA_OFF,
	GRAZYNA_BORYS_STASZEK_ON,
	GRAZYNA_BORYS_STASZEK_OFF,
	CHECK_WHO_IS_ONLINE = 8192,
	MANIEK_ONLINE
};

struct DATA_u8{
	uint8_t data[12];
};
struct DATA_u32_u16{
	uint32_t data_u32[2];
	uint16_t data_u16;
};

struct __attribute__((packed)) DATA_u16_u32{
	uint8_t type;
	uint8_t id;
	uint32_t data;
	uint32_t crc;
};
union FRAME{
	struct DATA_u8 data_u8;
	struct DATA_u32_u16 data_u32_u16;
	struct DATA_u16_u32 frame;
};
void SS_grazyna_init(void);
void SS_grazyna_handle_rx_cplt(void);		//called in interrupt, keep as short as possible
void SS_grazyna_handle_received(void);
void SS_grazyna_send_nack(void);
uint8_t SS_grazyna_get_valid_rcv_flag(void);
void SS_grazyna_frame_send(uint8_t header_type, uint8_t header_ID, uint32_t data);
void SS_grazyna_frame_send_u8(uint8_t header_type, uint8_t header_ID, uint8_t * data);
void SS_grazyna_handle_can(CAN_RxHeaderTypeDef rx_header, uint8_t *data);
void SS_servo_set_ignition_delay(uint16_t delay);
//void SS_grazyna_frame_send(union FRAME* tx_frame);




#endif /* SS_GRAZYNA_XBEE_H_ */
